#!/usr/bin/env bash
# Do our modules set ROKSBNKCTL_* variables the pinned runner still reads?
#
#   ./scripts/check-env-surface.sh          # uses the digest the modules pin
#
# WHY THIS ASKS THE BINARY
# roksbnkctl adds and REMOVES settings between releases, and a removed one fails
# silently: --override-from-env ignores what it does not know, so a module goes on
# offering an operator a control that does nothing. v1.54.0 removed
# bnk.flp.vsi.reach and v1.57.0 removed bnk.gtm; both sat in our blueprints
# afterwards, and nothing complained.
#
# `roksbnkctl config env` prints the annotated template of every setting, so the
# pinned image is its own source of truth. Grepping the roksbnkctl source instead
# gets this wrong: the per-zone family (ROKSBNKCTL_ZONE1_EXT_VLAN_CIDR and its 17
# siblings) is GENERATED by zoneOverrideNames(), so a literal grep reports 18
# live variables as dead.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$HERE/.." && pwd)"
DIGEST=$(python3 -c "
import json,glob
for f in glob.glob('$ROOT/roksbnkctl/*/bnkforge.artifact.json'):
    d=json.load(open(f))
    ci=d.get('container_image') or {}
    if ci.get('digest'): print(ci['digest']); break")
[[ -n "$DIGEST" ]] || { echo "no pinned runner digest found" >&2; exit 2; }
IMG="ghcr.io/jgruberf5/roksbnkctl-tools-runner@$DIGEST"
echo "  runner: $DIGEST"

KNOWN=$(timeout 300 docker run --rm "$IMG" config env 2>/dev/null \
        | grep -oE 'ROKSBNKCTL_[A-Z0-9_]+' | sort -u)
[[ -n "$KNOWN" ]] || { echo "could not read 'config env' from the runner" >&2; exit 2; }

OURS=$(python3 -c "
import json,glob
s=set()
for f in glob.glob('$ROOT/roksbnkctl/*/bnkforge.artifact.json'):
    d=json.load(open(f))
    for phase in d.get('steps',{}).values():
        for st in phase:
            s.update(k for k in (st.get('env') or {}) if k.startswith('ROKSBNKCTL_'))
print('\n'.join(sorted(s)))")

# ROKSBNKCTL_HOME configures the CLI's own workspace root, not a workspace
# setting, so it is legitimately absent from `config env`.
#
# DELIBERATELY NOT SURFACED, so the informational count is not mistaken for a gap:
#   tf_source.*   (v1.59.0) selects which Terraform the binary applies. The
#                 default `embedded` tree is, in roksbnkctl's own words, "the only
#                 version matched to it"; github and local are for testing a fork.
#                 Exposing it would let an operator repoint terraform at a tree the
#                 pinned runner digest does not determine, which is the whole
#                 reason these modules pin by digest rather than tag.
#   TESTING_*, CLIENT_VPC_*, TGW_JUMPHOST_*  configure the test client these
#                 blueprints do not drive.
#   BNKFORGE_*    already first-class blueprint inputs; a second route to one
#                 setting is a second thing that can disagree.
#   API_KEY_*, COPIED_SSH_KEY_FILES  supplied by the credential template.
DEAD=$(comm -23 <(printf '%s\n' "$OURS") <(printf '%s\n' "$KNOWN") | grep -v '^ROKSBNKCTL_HOME$' || true)
if [[ -n "$DEAD" ]]; then
  echo "  FAIL — set by our modules, not read by this runner:"
  printf '%s\n' "$DEAD" | sed 's/^/    /'
  exit 1
fi
echo "  OK — every ROKSBNKCTL_* our modules set is one this runner reads ($(printf '%s\n' "$OURS" | wc -l) variables)"
UNSURFACED=$(comm -13 <(printf '%s\n' "$OURS") <(printf '%s\n' "$KNOWN") | wc -l)
echo "  note: $UNSURFACED settings this runner offers are not surfaced by any module (informational)"
